version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bankcards-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 3s
      retries: 10

  app:
    build: .
    container_name: bankcards-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      # Hibernate DDL mode taken on application.yml (validate), but it is possible to redefine:
      # SPRING_JPA_HIBERNATE_DDL_AUTO: validate

      # === app.crypto ===
      AES_KEY_B64: ${AES_KEY_B64}

      # === app.jwt ===
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MINUTES: ${JWT_EXPIRATION_MINUTES}
    ports:
      - "${APP_PORT}:8080"
    restart: unless-stopped

volumes:
  db_data:
