spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
    open-in-view: false
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.xml

app:
  crypto:
    aes-key-b64: "_256_БИТНЫЙ_KEY_В_BASE64"

  jwt:
    secret: "вот здесь вот очень длинная-256-bit строка с JWT-токеном"
    expiration-minutes: 120
