spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: false

app:
  crypto:
    aes-key-b64: ${AES_KEY_B64:?MUST_SET_256_BIT_KEY_IN_BASE64}

  jwt:
    secret: ${JWT_SECRET:?MUST_SET_JWT_SECRET_256bit}
    expiration-minutes: ${JWT_EXPIRATION_MINUTES:120}
