spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bankdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    properties:
      hibernate:
        format_sql: true

app:
  crypto:
    aes-key-b64: ${AES_KEY_B64:} # empty — generated at startup

  jwt:
    secret: ${JWT_SECRET:m2m7xkQm7U6p0n0lM0b4m3h0bJ8i9e9ZQfJrQmV4S4A=} # test for dev
    expiration-minutes: ${JWT_EXPIRATION_MINUTES:120}
