spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
    open-in-view: false

  liquibase:
    change-log: classpath:db/migration/db.changelog-master.xml

app:
  jwt:
    expiration-minutes: 120
